### ISSUE TITLE
Sql Server with Instance

### ISSUE THREAD

**Issue by venurapereratlc** [imanuelcostigan/RSQLServer#104]
Hi 

This is a question rather than a issue. 

I want to connect to a instance on a server but it doesn't work. My yaml file looks like this
```
SQL_PROD:
    server: 192.168.5.170\HDMSQL
    port: 1433
    type: sqlserver
    domain: **********
    user: ***********
    password: ***********
    useNTLMv2: true
```

When I try to connect using:

`conn<-dbConnect(SQLServer(),"SQL_PROD")`

I have the error: 

```
Error in rJava::.jcall(drv@jdrv, "Ljava/sql/Connection;", "connect", url,  : 
  java.sql.SQLException: Unknown server host name '192.168.5.170\HDMSQL'.
```

Any help would be appreciated.
